version: "3.5"
services:
  postgres:
    image: postgres:latest
    domainname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student