server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        hbm2ddl:
          auto: update